apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cbrdsbiru-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cbrdsbiru-java-quarkus-gitops